# Generated by Django 3.2 on 2021-04-18 05:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='種別')),
                ('color', models.CharField(blank=True, max_length=20, null=True, verbose_name='色コード')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.today, max_length=255, verbose_name='日付')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='内容')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了')),
                ('activity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='cms.activitytype', verbose_name='種別')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cms.record', verbose_name='活動日')),
            ],
        ),
    ]
