# Generated by Django 3.2.2 on 2021-05-09 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='内容')),
                ('activity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_activities', to='cms.activitytype', verbose_name='種別')),
            ],
        ),
    ]
